---
name: App-Munchies
version: 0.1.678
author:
  - 'Peter Flanigan, C<< <Support at RoxSoft.co.uk> >>'
abstract: Catalyst example application using food recipes as a data set
license: perl
resources:
  license: http://dev.perl.org/licenses/
configure_requires:
  CatalystX::Usul: 0.1.437
  Module::Build: 0.31
  version: 0.74
requires:
  Authen::Simple: 0.4
  Catalyst::Authentication::Credential::Authen::Simple: 0.02
  CatalystX::Usul: 0.1.437
  DBI: 1.602
  Data::CloudWeights: 0.1.3
  Date::Discordian: 1.36
  DateTime::Event::Sunrise: 0.0501
  DateTime::Fiction::JRRTolkien::Shire: 0.02
  IO::Interactive: 0.0.3
  KinoSearch: 0.20_04
  MealMaster: 0.28
  Template::Stash: 2.9
  Text::Lorem::More: 0.12
  WWW::Wikipedia: 1.94
  perl: 5.008
  version: 0.74
build_requires:
  Test::More: 0.74
recommends:
  Authen::Simple::PAM: 0.2
provides:
  App::Munchies:
    file: lib/App/Munchies.pm
    version: 0.1.678
  App::Munchies::Controller::Admin:
    file: lib/App/Munchies/Controller/Admin.pm
    version: 0.1.639
  App::Munchies::Controller::Entrance:
    file: lib/App/Munchies/Controller/Entrance.pm
    version: 0.1.655
  App::Munchies::Controller::Library:
    file: lib/App/Munchies/Controller/Library.pm
    version: 0.1.639
  App::Munchies::Controller::Library::Admin:
    file: lib/App/Munchies/Controller/Library/Admin.pm
    version: 0.1.622
  App::Munchies::Controller::Library::Catalog:
    file: lib/App/Munchies/Controller/Library/Catalog.pm
    version: 0.1.639
  App::Munchies::Controller::Library::Recipes:
    file: lib/App/Munchies/Controller/Library/Recipes.pm
    version: 0.1.613
  App::Munchies::MealMaster::KinoSearch:
    file: lib/App/Munchies/MealMaster/KinoSearch.pm
    version: 0.1.643
  App::Munchies::Model::Authentication:
    file: lib/App/Munchies/Model/Authentication.pm
    version: 0.1.563
  App::Munchies::Model::Catalog:
    file: lib/App/Munchies/Model/Catalog.pm
    version: 0.1.655
  App::Munchies::Model::DemoText:
    file: lib/App/Munchies/Model/DemoText.pm
    version: 0.1.655
  App::Munchies::Model::MealMaster:
    file: lib/App/Munchies/Model/MealMaster.pm
    version: 0.1.655
  App::Munchies::Programs::Misc:
    file: lib/App/Munchies/Programs/Misc.pm
    version: 0.1.636
  App::Munchies::Programs::Suid:
    file: lib/App/Munchies/Programs/Suid.pm
    version: 0.1.639
  App::Munchies::Schema:
    file: lib/App/Munchies/Schema.pm
    version: 0.1.629
  App::Munchies::Schema::Authentication:
    file: lib/App/Munchies/Schema/Authentication.pm
    version: 0.1.636
  App::Munchies::Schema::Authentication::Roles:
    file: lib/App/Munchies/Schema/Authentication/Roles.pm
    version: 0.1.636
  App::Munchies::Schema::Authentication::UserRoles:
    file: lib/App/Munchies/Schema/Authentication/UserRoles.pm
    version: 0.1.636
  App::Munchies::Schema::Authentication::Users:
    file: lib/App/Munchies/Schema/Authentication/Users.pm
    version: 0.1.636
  App::Munchies::Schema::Base:
    file: lib/App/Munchies/Schema/Base.pm
    version: 0.1.636
  App::Munchies::Schema::Catalog:
    file: lib/App/Munchies/Schema/Catalog.pm
    version: 0.1.636
  App::Munchies::Schema::Catalog::Result::Links:
    file: lib/App/Munchies/Schema/Catalog/Result/Links.pm
    version: 0.1.636
  App::Munchies::Schema::Catalog::Result::Names:
    file: lib/App/Munchies/Schema/Catalog/Result/Names.pm
    version: 0.1.636
  App::Munchies::Schema::Catalog::Result::Nodes:
    file: lib/App/Munchies/Schema/Catalog/Result/Nodes.pm
    version: 0.1.636
  App::Munchies::Schema::Catalog::ResultSet::Links:
    file: lib/App/Munchies/Schema/Catalog/ResultSet/Links.pm
    version: 0.1.636
  App::Munchies::Schema::Catalog::ResultSet::Nodes:
    file: lib/App/Munchies/Schema/Catalog/ResultSet/Nodes.pm
    version: 0.1.636
generated_by: Module::Build version 0.31
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
